# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tensor_pb2 as tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x1a\x0ctensor.proto\"/\n\x11\x43heckBufferStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"#\n\x11\x42ufferStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x0bReduceChunk\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\x12\x1e\n\ndata_chunk\x18\x02 \x01(\x0b\x32\n.DataChunk\">\n\x0bGatherChunk\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\x12\x1e\n\ndata_chunk\x18\x02 \x01(\x0b\x32\n.DataChunk\"2\n\x0cWeightsChunk\x12\"\n\x0ctensor_chunk\x18\x02 \x01(\x0b\x32\x0c.TensorChunk\"<\n\tDataChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tdata_size\x18\x03 \x01(\x05\"\x1e\n\rReceivedChunk\x12\r\n\x05reply\x18\x01 \x01(\x08\"\'\n\x14\x43heckReduceIteration\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\")\n\x14ReduceIterationReply\x12\x11\n\titeration\x18\x01 \x01(\x05\"\'\n\x14\x43heckGatherIteration\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\")\n\x14GatherIterationReply\x12\x11\n\titeration\x18\x01 \x01(\x05\"(\n\x11SendLatestWeights\x12\x13\n\x0bparam_names\x18\x01 \x01(\x0c\"\x1b\n\x0bPingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x0cPingResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xc9\x03\n\nCommServer\x12\x30\n\x0bsend_buffer\x12\x0b.SendTensor\x1a\x10.SendTensorReply\"\x00(\x01\x12\x39\n\rbuffer_status\x12\x12.CheckBufferStatus\x1a\x12.BufferStatusReply\"\x00\x12\x30\n\x0creduce_chunk\x12\x0c.ReduceChunk\x1a\x0e.ReceivedChunk\"\x00(\x01\x12\x30\n\x0cgather_chunk\x12\x0c.GatherChunk\x1a\x0e.ReceivedChunk\"\x00(\x01\x12\x42\n\x10reduce_iteration\x12\x15.CheckReduceIteration\x1a\x15.ReduceIterationReply\"\x00\x12\x42\n\x10gather_iteration\x12\x15.CheckGatherIteration\x1a\x15.GatherIterationReply\"\x00\x12;\n\x12get_latest_weights\x12\x12.SendLatestWeights\x1a\r.WeightsChunk\"\x00\x30\x01\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKBUFFERSTATUS._serialized_start=30
  _CHECKBUFFERSTATUS._serialized_end=77
  _BUFFERSTATUSREPLY._serialized_start=79
  _BUFFERSTATUSREPLY._serialized_end=114
  _REDUCECHUNK._serialized_start=116
  _REDUCECHUNK._serialized_end=178
  _GATHERCHUNK._serialized_start=180
  _GATHERCHUNK._serialized_end=242
  _WEIGHTSCHUNK._serialized_start=244
  _WEIGHTSCHUNK._serialized_end=294
  _DATACHUNK._serialized_start=296
  _DATACHUNK._serialized_end=356
  _RECEIVEDCHUNK._serialized_start=358
  _RECEIVEDCHUNK._serialized_end=388
  _CHECKREDUCEITERATION._serialized_start=390
  _CHECKREDUCEITERATION._serialized_end=429
  _REDUCEITERATIONREPLY._serialized_start=431
  _REDUCEITERATIONREPLY._serialized_end=472
  _CHECKGATHERITERATION._serialized_start=474
  _CHECKGATHERITERATION._serialized_end=513
  _GATHERITERATIONREPLY._serialized_start=515
  _GATHERITERATIONREPLY._serialized_end=556
  _SENDLATESTWEIGHTS._serialized_start=558
  _SENDLATESTWEIGHTS._serialized_end=598
  _PINGREQUEST._serialized_start=600
  _PINGREQUEST._serialized_end=627
  _PINGRESPONSE._serialized_start=629
  _PINGRESPONSE._serialized_end=657
  _COMMSERVER._serialized_start=660
  _COMMSERVER._serialized_end=1117
# @@protoc_insertion_point(module_scope)
